name: Laravel CI

on:
  push:
    branches:
      - master  # Change to your default branch
  pull_request:
    branches:
      - master  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      APP_KEY: base64:GcPg4wWdicv1IKtMiCs+2HJ7X7GLmnaN+lqsSqe6U+I=

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, gd, curl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Laravel Pint
        run: composer exec pint

      - name: Run PHPStan
        run: composer exec phpstan analyse

      - name: Run Tests
        run: php artisan test

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
